#!/bin/bash
#
# Regression test for the MolDStruct MC/MD ionization module.
#
# Runs the shipped lysozyme example for a few hundred steps with the Monte
# Carlo seed pinned, and checks three things:
#
#   1. the four event counts match a stored reference exactly
#   2. net charge is conserved: sum(charges) == photoionizations + Auger
#   3. a run without -ionize writes no ionization output at all
#
# (1) is a bitwise check and is the point of the test: the module is
# stochastic, but with GMX_MCMD_SEED set it is deterministic, so any change
# that alters the physics moves these numbers. It is only meaningful against a
# reference generated by the same build on the same machine - a different
# compiler or optimisation level can shift the trajectory. Regenerate with
# --update when you change the physics deliberately, and say so in the commit.
#
# (2) holds regardless of build: every electron removed from an atom is either
# a photoionization or an Auger event, and charge transfer only moves charge
# between atoms. A failure here is a real bug, not a platform difference.
#
# Usage:
#   test/regression.sh [--bindir DIR] [--steps N] [--update] [--keep]
#
set -u

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BINDIR="$REPO/gromacs-4.5.4-MCMD/build/src/kernel"
STEPS=300
UPDATE=0
KEEP=0
SEED=12345

while [ $# -gt 0 ]; do
    case "$1" in
        --bindir) BINDIR="$2"; shift 2 ;;
        --steps)  STEPS="$2";  shift 2 ;;
        --update) UPDATE=1;    shift ;;
        --keep)   KEEP=1;      shift ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

REF="$REPO/test/reference_${STEPS}.txt"
WORK="$(mktemp -d)"
trap '[ "$KEEP" = 1 ] && echo "kept $WORK" || rm -rf "$WORK"' EXIT

for exe in pdb2gmx grompp mdrun; do
    if [ ! -x "$BINDIR/$exe" ]; then
        echo "FAIL: $exe not found in $BINDIR (pass --bindir)" >&2
        exit 2
    fi
done

export GMXLIB="${GMXLIB:-$REPO/gromacs-4.5.4-MCMD/share/top}"
export GMX_MCMD_SEED="$SEED"

cp -r "$REPO/example/Atomic_data" "$WORK/"
cp "$REPO/example/1aki.pdb" "$REPO/example/exp.mdp" "$WORK/"
cd "$WORK" || exit 2
mkdir -p simulation_output

echo "workdir  $WORK"
echo "binaries $BINDIR"
echo "steps    $STEPS, seed $SEED"
echo

run() { if ! "$@" >>setup.log 2>&1; then echo "FAIL: $1 failed, see $WORK/setup.log" >&2; KEEP=1; exit 1; fi; }

# -water none: the example runs in vacuum, and without the flag pdb2gmx
# prompts for a water model, which would hang an unattended run.
run "$BINDIR/pdb2gmx" -f 1aki.pdb -ff charmm27 -water none
sed -e "s/^nsteps.*/nsteps = $STEPS/" \
    -e "s/^mcmd-autostop  *=.*/mcmd-autostop = 0/" exp.mdp > run.mdp
run "$BINDIR/grompp" -f run.mdp -c conf.gro -p topol.top -o run.tpr -po out.mdp -maxwarn 30
run "$BINDIR/mdrun" -deffnm run -s run.tpr -nt 1 -ionize

STATS="$(tail -1 simulation_output/procces_statistics.txt)"
set -- $STATS
AUGER=$1; FLUOR=$2; PHOTO=$3; CT=$4

CHARGE_SUM="$(awk '{s+=$2} END{print s+0}' simulation_output/charges.txt)"
EXPECT=$((PHOTO + AUGER))

FAILED=0

echo "--- 1. event counts (auger fluorescence photoionization charge-transfer)"
if [ "$UPDATE" = 1 ]; then
    echo "$STATS" > "$REF"
    echo "    wrote reference: $REF"
    echo "    $STATS"
elif [ ! -f "$REF" ]; then
    echo "    SKIP: no reference at $REF (create it with --update)"
elif [ "$STATS" = "$(cat "$REF")" ]; then
    echo "    PASS  $STATS"
else
    echo "    FAIL  got      $STATS"
    echo "          expected $(cat "$REF")"
    FAILED=1
fi

echo "--- 2. charge conservation"
if [ "$CHARGE_SUM" = "$EXPECT" ]; then
    echo "    PASS  sum(charges) = $CHARGE_SUM = photoionization($PHOTO) + auger($AUGER)"
else
    echo "    FAIL  sum(charges) = $CHARGE_SUM, expected $EXPECT"
    FAILED=1
fi

echo "--- 3. no -ionize writes no ionization output"
rm -rf simulation_output
run "$BINDIR/mdrun" -deffnm plain -s run.tpr -nt 1
if [ -d simulation_output ]; then
    echo "    FAIL  simulation_output/ was created without -ionize"
    FAILED=1
else
    echo "    PASS"
fi

echo
if [ "$FAILED" = 0 ]; then echo "OK"; else echo "FAILURES"; KEEP=1; fi
exit $FAILED
